version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - database
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:3000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - myapp-network

  database:
    image: mongo
    restart: always
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD-SHELL", "mongo --eval \"printjson(db.serverStatus())\""]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - myapp-network

  # frontend:
  #   build:
  #     context: ./app/frontend
  #     dockerfile: Dockerfile
  #   image: frontEnd
      # depends_on:
      #   - backend
  #   ports:
  #     - "3001:3001"
  #   healthcheck:
  #     test: ["CMD-SHELL", "curl --fail http://localhost:80/health || exit 1"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 5
  #   networks:
  #     - myapp-network

volumes:
  mongodb-data:

networks:
  myapp-network: